# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the Next.js application
FROM node:16-alpine AS nextjs-builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Build the Tauri application
FROM rust:latest AS tauri-builder

WORKDIR /app

# Install the Tauri CLI
RUN cargo install tauri-cli

# Copy Next.js build output
COPY --from=nextjs-builder /app/dist ./dist

# Copy the rest of the application files
COPY src-tauri ./src-tauri

# Build the Tauri application
RUN tauri build

# Stage 3: Final stage
FROM scratch

# Copy the built application from the tauri-builder stage
COPY --from=tauri-builder /app/src-tauri/target/release/bundle /

# Command to run your application
ENTRYPOINT ["/your-binary-name"]
